name: Build Mobile Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:

      - name: 3. Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet==0.22.0 httpx

      - name: 4. Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.6' # Use a specific, known-good version

      - name: 5. Create pubspec override to fix webview issue
        run: |
          echo "dependency_overrides:" > pubspec.yaml.override
          echo "  webview_flutter: 3.0.4" >> pubspec.yaml.override
          echo "  webview_flutter_android: 3.12.1" >> pubspec.yaml.override
          echo "  webview_flutter_wkwebview: 3.9.4" >> pubspec.yaml.override
          cat pubspec.yaml.override

      - name: 6. Build APK
        run: |
          flet build apk --build-name 1.0.${{ github.run_number }} --build-number ${{ github.run_number }}
          # Rename for easier identification
          mv ./build/apk/app-release.apk ./build/apk/water-${{ github.sha }}.apk

      - name: 7. Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: ./build/apk/water-${{ github.sha }}.apk

  build-ipa:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 3. Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install flet==0.22.0 httpx

      - name: 4. Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.6' # Use the same version as Android for consistency

      - name: 5. Build IPA
        run: flet build ipa --build-name 1.0.${{ github.run_number }} --build-number ${{ github.run_number }}

      - name: 6. Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-ipa
          path: build/ipa/app.ipa # Flet now creates app.ipa directly
